### ISSUE TITLE
Tab Visibility

### ISSUE THREAD

**Issue by felipechavez** [rajeshangappan/Xamarin#1]
Hi, first of all, thanks for the work done in this functionality. It helped me alot!. @rajeshangappan . 

But actually, I found something that could be improved, which is about the visibility of the tab. 
The problem was that I added visibility to the header control in a tab and it only left an empty space.

Have you a great day.!

**Comment by rajeshangappan** [comment]
Oh okay. I will check and add the tab header visibility support soon.

**Comment by felipechavez** [comment]
let me know if you need some help. i download your repo, and modify some code for test in my local environment and works good. i can send you a pr for your approvation as well

**Comment by felipechavez** [comment]
Not working with Bindings :(

**Comment by rajeshangappan** [comment]
Binding support added.
