### ISSUE TITLE
TabControl Bindings not Working

### ISSUE THREAD

**Issue by 3venjd** [rajeshangappan/Xamarin#4]
Hello friend.

already i can use bindings inside the tabview more specific in the tabheader but now i need to bind SelectedItem in the TabControl, but this not working.

in codebehind works amazing! but when is used mvvm is the only property that doesn't works

can you help with that?

![TabViewIssue](https://user-images.githubusercontent.com/31141661/86495726-28e6ea80-bd40-11ea-915e-cbfa04f4c202.png)

Thanks for all

pd: this control is the best! that i saw! please don't forget it!!

**Comment by rajeshangappan** [comment]
I will check and let you know.

**Comment by rajeshangappan** [comment]
Index binding issue resolved in latest source. Please check the latest nuget

**Comment by 3venjd** [comment]
Amazing!!!!!!!!!! , is working now,  thanks a lot!!! you are a goat!!
