### ISSUE TITLE
why you use contentpage?

### ISSUE THREAD

**Issue by EmilAlipiev** [rajeshangappan/Xamarin#5]
why there is field  ` internal ContentPage m_content;`
You create a page object and use only content part of it which is contentview? why dont use just use contentview :)
This can be even more memory friendly and easier to understand. is there any reason I am missing to define as contentpage?

**Comment by rajeshangappan** [comment]
Yes, ultimately we can use this tab view for your base layout or child control. Same like tabbed page in xamarin forms or tab view control (part of any page).
