### ISSUE TITLE
Header height and Selector height not working

### ISSUE THREAD

**Issue by zhengzheli** [rajeshangappan/Xamarin#6]
Hello,

Thank you for this plugin. It is working well. I was wondering though, if the header and selector height are working yet? They seem to have no effect.

Thanks,

Philip

**Comment by rajeshangappan** [comment]
Hi Philp,
   I will check once again and update you.

**Comment by boutch57** [comment]
Hello, having the same issue. For me it's only the selector height which don't work, changing value for SelectorHeight has no effect. Please can you fixed it. Tested on Android API 30 and iOS 14.2
Also it would be nice to have a custom view for header like custom content page
Thanks,
Bryan

**Comment by rajeshangappan** [comment]
Okay sure. Working on it will update within 2 days

**Comment by rajeshangappan** [comment]
Hi All, 
I have added the below property to achieve the selector height. also, added the support for pagination bgcolor.
1.HeaderSelectorHeight
2.PaginatorBackgroundColor
Please use the 1.0.2 version.
